# Generated by Django 5.2 on 2025-05-14 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cet_physics', models.IntegerField()),
                ('cet_chemistry', models.IntegerField()),
                ('cet_math', models.IntegerField()),
                ('puc_physics', models.IntegerField()),
                ('puc_chemistry', models.IntegerField()),
                ('puc_math', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
